services:
  - type: web
    name: telefavor-bot
    env: node
    buildCommand: npm install
    startCommand: node telegram-bot.cjs
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: VERIFY_URL
        sync: false
